### ISSUE TITLE
Missing train.json, val.json and test.json files

### ISSUE THREAD

**Issue by KushRavi23** [Iywie/pl_YOLO#1]
annotations/train.json file is located in dir: 'D:\Code\Datasets\Detection\COCO2017'. It should be present in the repository.
Need all the train.json, val.json and test.json files.

**Comment by Iywie** [comment]
This COCO2017.yaml file has now been modified correctly, no additional json is needed, just use the instances_train2017.json of COCO2017.
The dataset directory structure can be found in the readme.

**Comment by KushRavi23** [comment]
Thanks @Iywie
